apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: npedc25ji-nodejs
  janus-idp.io/tekton: npedc25ji-nodejs
  backstage.io/kubernetes-id: npedc25ji-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: npedc25ji-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
