apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: npedc25ji-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: npedc25ji-nodejs 
  name: npedc25ji-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: npedc25ji-nodejs 
